# Generated by Django 5.2.16 on 2026-07-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
